name: JavaScript files

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '8.x', '10.x', '12.x', '14.x' ]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: '${{ matrix.node }}'
    - name: Build
      run: make build
    - name: Test
      run: make test
