name: JavaScript files

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Node 8.x
      uses: actions/setup-node@v1
      with:
        node-version: '8.x'
    - name: Build
      run: make build
    - name: Test
      run: make test
